site_name: 'Go reading list'
site_description: 'HelloFresh guides for Go projects and developers'

plugins:
  - techdocs-core

markdown_extensions:
  - admonition

nav:
  - Home: 'docs/README.md'
  - Best Practices: 'docs/best_practices.md'
  - Code Style: 'docs/code_style.md'
  - Directory Structure: 'docs/directory_structure.md'
  - Packages: 'docs/packages.md'
  - Projects: 'docs/projects.md'
  - Reading List: 'docs/reading_list.md'
  - Tools: 'docs/tools.md'
